spring:
  port: 8080
  application:
    name: twitter-clone-users-service
  jackson:
    default-property-inclusion: NON_NULL
  r2dbc:
    url: ${DB_HOST:r2dbc:postgresql://localhost:5432/tc_users_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
logging:
  level:
    root: INFO
    com.fernando.ms.users.app: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql
